version: '3.8'

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
      - postgres:/var/lib/postgresql/data
    healthcheck:
      interval: 5s
      retries: 5
    restart: always

  pgadmin:
    image: dpage/pgadmin4:6.20
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  app:
    build: .
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    env_file:
      - .env

volumes:
  postgres:
  pgadmin-data: